<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Settings\UserSettings $userSettings
 * @var array $idpAttributesToSettingsKeys
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
?>

<div class="meta-group sso-profile">
    <h4><?= $translate('Single Sign-On') ?></h4>
    <div class="value sso-account">
        <?php foreach ($idpAttributesToSettingsKeys as $idpAttribute => $settingKey):
            $vals = $userSettings->get($settingKey);
            if ($vals === null || $vals === '' || $vals === []) continue;
            if (!is_array($vals)) $vals = [$vals];
            ?>
            <div>
                <?= sprintf($translate('%1$s: %2$s'), '<span class="value-key">' . $escape($idpAttribute) . '</span>', '<span class="value-value">' . implode('</span>, <span class="value-value">', array_map($escape, $vals)) . '</span>') ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
