<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\LoginForm $form
 *
 * Copy of omeka view template, with a check to disable form when local login is disabled.
 */

$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$translate = $plugins->get('translate');

// The main config is not easy to get from the view without deprecation warning.
$config = $api->read('vocabularies', 1)->getContent()->getServiceLocator()->get('Config');
$allowLocalLogin = empty($config['authentication']['forbid_local_login']);

$this->htmlElement('body')->appendAttribute('class', 'activate');
$form->prepare();
?>

<h1><?= $translate('Create a new password') ?></h1>

<?php if ($allowLocalLogin): ?>

<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<button><?= $translate('Activate') ?></button>
<?= $this->form()->closeTag() ?>

<?php else: ?>

<p><?= $translate('Create your password via your identity provider.') ?></p>

<?php endif; ?>
